version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000:/run/user/1000
    ports:
      - "8888:8888"
    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
